export const FETCH_COLLECTIONS_START = "FETCH_COLLECTIONS_START"
export const FETCH_COLLECTIONS_FAILURE = "FETCH_COLLECTIONS_FAILURE"
export const FECTH_COLLECTIONS_SUCCESS = "FECTH_COLLECTIONS_SUCCESS"