export const ADD_ITEM = "ADD_ITEM"
export const TOGGLE_CART_HIDDEN = "TOGGLE_CART_HIDDEN"
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART"
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART"
