export const cartActionTypes = {
  ADD_ITEM: "ADD_ITEM",
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART"
}

